-- @version 		$Id:$
-- @name			TSJ CDMX Libros TxCA (Release 1.0.0)
-- @author			caballeroantonio (caballeroantonio.com)
-- @package			com_jtca
-- @subpackage		com_jtca.admin
-- @copyright		Copyright (c) 2017 - 2020. All Rights Reserved
-- @license			GNU General Public License version 3 or later - See http://www.gnu.org/copyleft/gpl.html 
--
-- The following Component Architect header section must remain in any distribution of this file
--
-- @CAversion		Id:uninstall.architectcomp_mysql.utf8.sql 19 2012-01-12 16:33:49Z BrianWade $
-- @CAauthor		Component Architect (www.componentarchitect.com)
-- @CApackage		architectcomp
-- @CAsubpackage	architectcomp.admin
-- @CAtemplate		joomla_3_4_standard (Release 1.0.1)
-- @CAcopyright		Copyright (c)2013 - 2016  Simply Open Source Ltd. (trading as Component Architect). All Rights Reserved
-- @CAlicense		GNU General Public License version 3 or later - See http://www.gnu.org/copyleft/gpl.html
--
-- This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
-- --------------------------------------------------------
--
-- Uninstall of `#__jtca` tables
--
DROP TABLE IF EXISTS `jt_lsc01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp19s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp19';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP19S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp20s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp20';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP20S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp21s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp21';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP21S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp22s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp22';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP22S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp23s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp23';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP23S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp24s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp24';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP24S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp25s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp25';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP25S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp26s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp26';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP26S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp27s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp27';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP27S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp28s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp28';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP28S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp29s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp29';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP29S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp30s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp30';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP30S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp31s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp31';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP31S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp32s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp32';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP32S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp33s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp33';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP33S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp34s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp34';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP34S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp35s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp35';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP35S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp36s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp36';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP36S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp39s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp39';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP39S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp40s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp40';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP40S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lcp41s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lcp41';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LCP41S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe01s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe01';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE01S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lspe08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lspe08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSPE08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst02s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst02';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST02S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lejemplos`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lejemplo';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LEJEMPLOS' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst03s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst03';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST03S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst04s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst04';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST04S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst05s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst05';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST05S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst06s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst06';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST06S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst07s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst07';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST07S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst08s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst08';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST08S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst09s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst09';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST09S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst10s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst10';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST10S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst11s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst11';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST11S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadng12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadng12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADNG12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljemst12s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljemst12';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJEMST12S' AND `type`='component';
DROP TABLE IF EXISTS `jt_lsc13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.lsc13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LSC13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf13s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf13';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF13S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljoc14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljoc14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOC14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf14s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf14';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF14S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf15s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf15';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF15S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf16s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf16';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF16S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljccm17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljccm17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJCCM17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf17s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf17';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF17S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpdng18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpdng18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPDNG18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljjadg18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljjadg18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJJADG18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljpes18s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljpes18';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJPES18S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc19s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc19';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC19S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf19s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf19';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF19S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp19s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp19';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP19S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf19s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf19';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF19S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc20s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc20';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC20S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf20s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf20';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF20S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp20s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp20';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP20S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf20s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf20';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF20S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljc21s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljc21';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJC21S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf21s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf21';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF21S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljp21s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljp21';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJP21S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf21s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf21';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF21S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljf22s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljf22';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJF22S' AND `type`='component';
DROP TABLE IF EXISTS `jt_ljomf22s`;
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.ljomf22';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_LJOMF22S' AND `type`='component';


DELETE FROM `#__assets` WHERE `name` LIKE '%com_jtca%';
DELETE FROM `#__extensions` WHERE `name`='com_jtca' AND `type`='component';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA' AND `type`='component';

#[ %%IF GENERATE_CATEGORIES%%] 
DELETE FROM `#__categories` WHERE `extension`='com_jtca';
DELETE FROM #__content_types WHERE `type_alias` = 'com_jtca.category';
DELETE FROM `#__menu` WHERE `title`='COM_JTCA_CATEGORIES' AND `type`='component';
#[ %%ENDIF GENERATE_CATEGORIES%%]
